"""init

Revision ID: 32c438b425b6
Revises:
Create Date: 2026-03-10 07:42:23.253681

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32c438b425b6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "common_link_type",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "common_object_type",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "english_acquisition",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "domain",
            sa.Enum("grammar", "lexis", "phonology", name="englishsystem"),
            nullable=False,
        ),
        sa.Column("item", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stage", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("frequency", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_english_acquisition_learner_id"),
        "english_acquisition",
        ["learner_id"],
        unique=False,
    )
    op.create_table(
        "english_practice",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "domain",
            sa.Enum("grammar", "lexis", "phonology", name="englishsystem"),
            nullable=False,
        ),
        sa.Column("item", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "arpabet_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "cefr_level",
            sa.Enum("a1", "a2", "b1", "b2", "c1", "c2", name="cefrlevel"),
            nullable=True,
        ),
        sa.Column("practiced_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_english_practice_learner_id"),
        "english_practice",
        ["learner_id"],
        unique=False,
    )
    op.create_table(
        "english_source",
        sa.Column(
            "source_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column(
            "exam_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("academic_year", sa.Integer(), nullable=True),
        sa.Column("form", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("issuer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "source_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("source_id"),
    )
    op.create_table(
        "error_prior",
        sa.Column(
            "cefr_level",
            sa.Enum("a1", "a2", "b1", "b2", "c1", "c2", name="cefrlevel"),
            nullable=False,
        ),
        sa.Column(
            "question_type",
            sa.Enum(
                "main_idea",
                "title",
                "detail",
                "inference",
                "vocabulary",
                "grammar",
                "ordering",
                "insertion",
                "summary",
                "blank_filling",
                "long_answer",
                name="questiontype",
            ),
            nullable=False,
        ),
        sa.Column("error_rate", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cefr_level", "question_type"),
    )
    op.create_table(
        "essay_outcome",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("accuracy", sa.Float(), nullable=False),
        sa.Column("vocabulary", sa.Float(), nullable=False),
        sa.Column("coherence", sa.Float(), nullable=False),
        sa.Column("task_completion", sa.Float(), nullable=False),
        sa.Column(
            "feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("assessed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_essay_outcome_learner_id"),
        "essay_outcome",
        ["learner_id"],
        unique=False,
    )
    op.create_table(
        "exam_period",
        sa.Column(
            "grade_tag",
            sa.Enum(
                "grade_10", "grade_11", "grade_12", "adult", name="gradetag"
            ),
            nullable=False,
        ),
        sa.Column(
            "exam_type",
            sa.Enum(
                "midterm", "final", "suneung_mock", "suneung", name="examtype"
            ),
            nullable=False,
        ),
        sa.Column("semester", sa.Integer(), nullable=False),
        sa.Column("exam_start", sa.Date(), nullable=False),
        sa.Column("exam_end", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fsrs_config",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "w_vector", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fsrs_config_learner_id"),
        "fsrs_config",
        ["learner_id"],
        unique=True,
    )
    op.create_table(
        "grammar_item",
        sa.Column(
            "curriculum_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("session_number", sa.Integer(), nullable=False),
        sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "book_units", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("curriculum_id", "session_number"),
    )
    op.create_index(
        op.f("ix_grammar_item_curriculum_id"),
        "grammar_item",
        ["curriculum_id"],
        unique=False,
    )
    op.create_table(
        "learner_exam_override",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("exam_start", sa.Date(), nullable=False),
        sa.Column("exam_end", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learner_exam_override_learner_id"),
        "learner_exam_override",
        ["learner_id"],
        unique=False,
    )
    op.create_table(
        "learner_proficiency",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "skill",
            sa.Enum(
                "reading", "writing", "listening", "speaking", name="skill"
            ),
            nullable=False,
        ),
        sa.Column(
            "cefr_level",
            sa.Enum("a1", "a2", "b1", "b2", "c1", "c2", name="cefrlevel"),
            nullable=False,
        ),
        sa.Column("assessed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learner_proficiency_learner_id"),
        "learner_proficiency",
        ["learner_id"],
        unique=False,
    )
    op.create_table(
        "learner_profile",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "cefr_level",
            sa.Enum("a1", "a2", "b1", "b2", "c1", "c2", name="cefrlevel"),
            nullable=False,
        ),
        sa.Column(
            "grade_tag",
            sa.Enum(
                "grade_10", "grade_11", "grade_12", "adult", name="gradetag"
            ),
            nullable=False,
        ),
        sa.Column(
            "schedule_days", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("session_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learner_profile_learner_id"),
        "learner_profile",
        ["learner_id"],
        unique=True,
    )
    op.create_table(
        "lesson_log",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "session_type",
            sa.Enum("regular", "exam_prep", name="sessiontype"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lesson_log_learner_id"),
        "lesson_log",
        ["learner_id"],
        unique=False,
    )
    op.create_table(
        "lexis_corpus_freq",
        sa.Column(
            "headword", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "corpus_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "cefr_level", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("freq", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("headword", "corpus_name", "cefr_level"),
    )
    op.create_table(
        "needs_analysis",
        sa.Column(
            "cefr_level",
            sa.Enum("a1", "a2", "b1", "b2", "c1", "c2", name="cefrlevel"),
            nullable=False,
        ),
        sa.Column(
            "english_skill",
            sa.Enum(
                "reading", "writing", "listening", "speaking", name="skill"
            ),
            nullable=True,
        ),
        sa.Column(
            "english_system",
            sa.Enum("grammar", "lexis", "phonology", name="englishsystem"),
            nullable=True,
        ),
        sa.Column("skill_weight", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "question_log",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "task_item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_log_learner_id"),
        "question_log",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_log_task_item_id"),
        "question_log",
        ["task_item_id"],
        unique=False,
    )
    op.create_table(
        "recall_event",
        sa.Column(
            "actor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "chat_recall", "quiz_response", "manual", name="recalleventtype"
            ),
            nullable=False,
        ),
        sa.Column(
            "task_item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recall_event_actor_id"),
        "recall_event",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recall_event_occurred_at"),
        "recall_event",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recall_event_processed"),
        "recall_event",
        ["processed"],
        unique=False,
    )
    op.create_table(
        "response_log",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "task_item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("answer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("duration_sec", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("recall", "direct", name="recallsource"),
            nullable=False,
        ),
        sa.Column("responded_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_response_log_learner_id"),
        "response_log",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_response_log_task_item_id"),
        "response_log",
        ["task_item_id"],
        unique=False,
    )
    op.create_table(
        "review_schedule",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "task_item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("stability", sa.Float(), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column("retrievability", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_schedule_due_date"),
        "review_schedule",
        ["due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_schedule_learner_id"),
        "review_schedule",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_schedule_task_item_id"),
        "review_schedule",
        ["task_item_id"],
        unique=False,
    )
    op.create_table(
        "task_outcome",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("session_at", sa.DateTime(), nullable=False),
        sa.Column(
            "task_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("outcome_correct", sa.Boolean(), nullable=True),
        sa.Column(
            "answer_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "skill",
            sa.Enum(
                "reading", "writing", "listening", "speaking", name="skill"
            ),
            nullable=True,
        ),
        sa.Column(
            "system",
            sa.Enum("grammar", "lexis", "phonology", name="englishsystem"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_outcome_learner_id"),
        "task_outcome",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_outcome_session_at"),
        "task_outcome",
        ["session_at"],
        unique=False,
    )
    op.create_table(
        "writing_assessment",
        sa.Column(
            "learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("session_at", sa.DateTime(), nullable=False),
        sa.Column(
            "task_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("content", sa.Integer(), nullable=False),
        sa.Column("grammar", sa.Integer(), nullable=False),
        sa.Column("lexical_resource", sa.Integer(), nullable=False),
        sa.Column("organization", sa.Integer(), nullable=False),
        sa.Column("english_total", sa.Integer(), nullable=False),
        sa.Column(
            "cefr_writing",
            sa.Enum("a1", "a2", "b1", "b2", "c1", "c2", name="cefrlevel"),
            nullable=True,
        ),
        sa.Column(
            "feedback_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "answer_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_writing_assessment_learner_id"),
        "writing_assessment",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_writing_assessment_session_at"),
        "writing_assessment",
        ["session_at"],
        unique=False,
    )
    op.create_table(
        "common_concept",
        sa.Column(
            "scheme_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scheme_id"],
            ["common_object_type.id"],
        ),
        sa.PrimaryKeyConstraint("scheme_id", "level"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("common_concept")
    op.drop_index(
        op.f("ix_writing_assessment_session_at"),
        table_name="writing_assessment",
    )
    op.drop_index(
        op.f("ix_writing_assessment_learner_id"),
        table_name="writing_assessment",
    )
    op.drop_table("writing_assessment")
    op.drop_index(op.f("ix_task_outcome_session_at"), table_name="task_outcome")
    op.drop_index(op.f("ix_task_outcome_learner_id"), table_name="task_outcome")
    op.drop_table("task_outcome")
    op.drop_index(
        op.f("ix_review_schedule_task_item_id"), table_name="review_schedule"
    )
    op.drop_index(
        op.f("ix_review_schedule_learner_id"), table_name="review_schedule"
    )
    op.drop_index(
        op.f("ix_review_schedule_due_date"), table_name="review_schedule"
    )
    op.drop_table("review_schedule")
    op.drop_index(
        op.f("ix_response_log_task_item_id"), table_name="response_log"
    )
    op.drop_index(op.f("ix_response_log_learner_id"), table_name="response_log")
    op.drop_table("response_log")
    op.drop_index(op.f("ix_recall_event_processed"), table_name="recall_event")
    op.drop_index(
        op.f("ix_recall_event_occurred_at"), table_name="recall_event"
    )
    op.drop_index(op.f("ix_recall_event_actor_id"), table_name="recall_event")
    op.drop_table("recall_event")
    op.drop_index(
        op.f("ix_question_log_task_item_id"), table_name="question_log"
    )
    op.drop_index(op.f("ix_question_log_learner_id"), table_name="question_log")
    op.drop_table("question_log")
    op.drop_table("needs_analysis")
    op.drop_table("lexis_corpus_freq")
    op.drop_index(op.f("ix_lesson_log_learner_id"), table_name="lesson_log")
    op.drop_table("lesson_log")
    op.drop_index(
        op.f("ix_learner_profile_learner_id"), table_name="learner_profile"
    )
    op.drop_table("learner_profile")
    op.drop_index(
        op.f("ix_learner_proficiency_learner_id"),
        table_name="learner_proficiency",
    )
    op.drop_table("learner_proficiency")
    op.drop_index(
        op.f("ix_learner_exam_override_learner_id"),
        table_name="learner_exam_override",
    )
    op.drop_table("learner_exam_override")
    op.drop_index(
        op.f("ix_grammar_item_curriculum_id"), table_name="grammar_item"
    )
    op.drop_table("grammar_item")
    op.drop_index(op.f("ix_fsrs_config_learner_id"), table_name="fsrs_config")
    op.drop_table("fsrs_config")
    op.drop_table("exam_period")
    op.drop_index(
        op.f("ix_essay_outcome_learner_id"), table_name="essay_outcome"
    )
    op.drop_table("essay_outcome")
    op.drop_table("error_prior")
    op.drop_table("english_source")
    op.drop_index(
        op.f("ix_english_practice_learner_id"), table_name="english_practice"
    )
    op.drop_table("english_practice")
    op.drop_index(
        op.f("ix_english_acquisition_learner_id"),
        table_name="english_acquisition",
    )
    op.drop_table("english_acquisition")
    op.drop_table("common_object_type")
    op.drop_table("common_link_type")
    # ### end Alembic commands ###
